### ISSUE TITLE
Hyperparams-tuning scripts using Optuna

### ISSUE THREAD

**Issue by blgpb** [yuziGuo/FarOptBasis#1]
Dear Guo,

I have read your paper "Graph Neural Networks with Learnable and Optimal Polynomial Bases". It is a very nice work! I have learned a lot from it.

However, I want to test FavardGNN and OptBasisGNN on other datasets, I might need the Optuna script for hyperparameter tuning.

Can you help me figure out this problem? Thank you very much!

PS: Your provided email address is not accessible.

**Comment by yuziGuo** [comment]
Thanks for reaching out.

Have sent a script for Optuna script for hyperparameter tuning, and a general framework for playing with polynomial filters is coming soon.
